server:
  port: 8083

topics:
  reserve: account.reserve
  commit: account.commit
  release: account.release

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/accountdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    liquibase:
      enabled: true
    properties:
      hibernate:
        use_new_id_generator_mappings: true

